[features]
seeds = false
skip-lint = false
[programs.localnet]
vrf_client = "D79gSNtjonBFmDfc4zznoYaJHPwGTb35zHQ1EPUPsxxp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/gally/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
